#!/usr/bin/env node
/*
 * Patches android/app/build.gradle (generated by `expo prebuild`) so that the
 * release build type is signed with our release keystore instead of the debug key.
 *
 * Signing values are read from gradle properties (PANTAU_UPLOAD_*), which CI
 * appends to android/gradle.properties from GitHub Secrets. If those properties
 * are absent (e.g. a local debug build), the release config falls back to the
 * debug keystore so nothing breaks.
 */
const fs = require("fs");
const path = require("path");

const gradlePath = path.join("android", "app", "build.gradle");
let src = fs.readFileSync(gradlePath, "utf8");

if (src.includes("PANTAU_UPLOAD_STORE_FILE")) {
  console.log("Signing config already present, skipping patch.");
  process.exit(0);
}

// 1) Point the release build TYPE at signingConfigs.release.
//    Do this FIRST, while the only `release {` block in the file is the
//    buildTypes one (signingConfigs currently only defines `debug`).
const releaseBuildTypeRe = /(release\s*\{[\s\S]*?signingConfig\s+signingConfigs\.)debug/;
if (releaseBuildTypeRe.test(src)) {
  src = src.replace(releaseBuildTypeRe, "$1release");
} else {
  console.error(
    "WARNING: release buildType signingConfig not found in expected form; build may sign with debug key."
  );
}

// 2) Add a `release` signing config inside the existing `signingConfigs { ... }` block.
const releaseSigningConfig = `
        release {
            if (project.hasProperty('PANTAU_UPLOAD_STORE_FILE')) {
                storeFile file(PANTAU_UPLOAD_STORE_FILE)
                storePassword PANTAU_UPLOAD_STORE_PASSWORD
                keyAlias PANTAU_UPLOAD_KEY_ALIAS
                keyPassword PANTAU_UPLOAD_KEY_PASSWORD
            } else {
                // Fallback so local/debug builds still work without secrets.
                storeFile file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }`;

const signingConfigsIdx = src.indexOf("signingConfigs {");
if (signingConfigsIdx === -1) {
  console.error("ERROR: could not find `signingConfigs {` in build.gradle");
  process.exit(1);
}
const insertAt = src.indexOf("{", signingConfigsIdx) + 1;
src = src.slice(0, insertAt) + releaseSigningConfig + src.slice(insertAt);

fs.writeFileSync(gradlePath, src);
console.log("Patched android/app/build.gradle for release signing.");
